export const ScreenNames = {
  MainScreen: "MainPage",
  PlatformSetupScreen: "PlatformSetup",
  PlatformSettingScreen: "PlatformSetting",
  PlatformInfoScreen: "PlatformInfo",
  TestAppScreen: "TestApp",
  HttpServerWebView: "HttpServerWebView",
  LedStripController: "LedStripController",
  EnvironmentMonitorScreen: "EnvironmentMonitor",
  RemoteCameraScreen: "RemoteCamera",
  PowerControllerScreen: "PowerController",
  ProvisionStartScreen: "ProvisionStartScreen",
  ProvisionModeSelectScreen: "ProvisionModeSelectScreen",
  ProvisionConnectWifiScreen: "ProvisionConnectWifiScreen",
  ProvisionSetWifiPasswordScreen: "ProvisionSetWifiPasswordScreen",
  ProvisionFinishScreen: "ProvisionFinishScreen",
};
