export const ScreenNames = {
  MainScreen: "MainPage",
  PlatformSetupScreen: "PlatformSetup",
  PlatformSettingScreen: "PlatformSetting",
  PlatformInfoScreen: "PlatformInfo",
  TestAppScreen: "TestApp",
  HttpServerWebView: "HttpServer",
  LedStripController: "LedStripController",
  EnvironmentMonitorScreen: "EnvironmentMonitor",
  RemoteCameraScreen: "RemoteCamera",
  PowerControllerScreen: "PowerController",
  ProvisionStartScreen: "ProvisionStartScreen",
  ProvisionModeSelectScreen: "ProvisionModeSelectScreen",
  ConnectWifiScreen: "ConnectWifiScreen",
  SetWifiPasswordScreen: "SetWifiPasswordScreen",
  ProvisionFinishScreen: "ProvisionFinishScreen",
};
