// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class FlatbuffersStreamAck {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):FlatbuffersStreamAck {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsFlatbuffersStreamAck(bb:flatbuffers.ByteBuffer, obj?:FlatbuffersStreamAck):FlatbuffersStreamAck {
  return (obj || new FlatbuffersStreamAck()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsFlatbuffersStreamAck(bb:flatbuffers.ByteBuffer, obj?:FlatbuffersStreamAck):FlatbuffersStreamAck {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new FlatbuffersStreamAck()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startFlatbuffersStreamAck(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endFlatbuffersStreamAck(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createFlatbuffersStreamAck(builder:flatbuffers.Builder):flatbuffers.Offset {
  FlatbuffersStreamAck.startFlatbuffersStreamAck(builder);
  return FlatbuffersStreamAck.endFlatbuffersStreamAck(builder);
}
}
