// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class FlatbuffersUnsubscribe {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):FlatbuffersUnsubscribe {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsFlatbuffersUnsubscribe(bb:flatbuffers.ByteBuffer, obj?:FlatbuffersUnsubscribe):FlatbuffersUnsubscribe {
  return (obj || new FlatbuffersUnsubscribe()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsFlatbuffersUnsubscribe(bb:flatbuffers.ByteBuffer, obj?:FlatbuffersUnsubscribe):FlatbuffersUnsubscribe {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new FlatbuffersUnsubscribe()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * kind: defines what type messages clients are subscribing for (stream vs command)
 * as well as the type of exchange for command messages
 */
kind():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

/**
 * name: name of the queue that will be declared and bind to the topics
 */
name(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

nameLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

nameArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

/**
 * error: If the server denied the subscription sends an error
 */
error(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

errorLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

errorArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startFlatbuffersUnsubscribe(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addKind(builder:flatbuffers.Builder, kind:number) {
  builder.addFieldInt8(0, kind, 0);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, nameOffset, 0);
}

static createNameVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startNameVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addError(builder:flatbuffers.Builder, errorOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, errorOffset, 0);
}

static createErrorVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startErrorVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static endFlatbuffersUnsubscribe(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createFlatbuffersUnsubscribe(builder:flatbuffers.Builder, kind:number, nameOffset:flatbuffers.Offset, errorOffset:flatbuffers.Offset):flatbuffers.Offset {
  FlatbuffersUnsubscribe.startFlatbuffersUnsubscribe(builder);
  FlatbuffersUnsubscribe.addKind(builder, kind);
  FlatbuffersUnsubscribe.addName(builder, nameOffset);
  FlatbuffersUnsubscribe.addError(builder, errorOffset);
  return FlatbuffersUnsubscribe.endFlatbuffersUnsubscribe(builder);
}
}
