// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class FlatbuffersStream {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):FlatbuffersStream {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsFlatbuffersStream(bb:flatbuffers.ByteBuffer, obj?:FlatbuffersStream):FlatbuffersStream {
  return (obj || new FlatbuffersStream()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsFlatbuffersStream(bb:flatbuffers.ByteBuffer, obj?:FlatbuffersStream):FlatbuffersStream {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new FlatbuffersStream()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * created_at: unit timestamp when message was created
 */
createdAt():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

/**
 * payload: opaque message payload as byte array
 */
payload(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

payloadLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

payloadArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

/**
 * device_type: device identity coming from the certificate derived of Issuer CN
 */
deviceType(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

deviceTypeLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

deviceTypeArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

/**
 * device_id: device identity coming from the certificate derived of Subject CN
 */
deviceId(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

deviceIdLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

deviceIdArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

/**
 * delivered_at_epoch_ms: timestamp at which the message reached the backend
 */
deliveredAtEpochMs():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

/**
 * expiry: unix timestamp after when to destroy the message
 */
expiry():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startFlatbuffersStream(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addCreatedAt(builder:flatbuffers.Builder, createdAt:number) {
  builder.addFieldInt32(0, createdAt, 0);
}

static addPayload(builder:flatbuffers.Builder, payloadOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, payloadOffset, 0);
}

static createPayloadVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startPayloadVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addDeviceType(builder:flatbuffers.Builder, deviceTypeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, deviceTypeOffset, 0);
}

static createDeviceTypeVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startDeviceTypeVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addDeviceId(builder:flatbuffers.Builder, deviceIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, deviceIdOffset, 0);
}

static createDeviceIdVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startDeviceIdVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addDeliveredAtEpochMs(builder:flatbuffers.Builder, deliveredAtEpochMs:bigint) {
  builder.addFieldInt64(4, deliveredAtEpochMs, BigInt('0'));
}

static addExpiry(builder:flatbuffers.Builder, expiry:number) {
  builder.addFieldInt32(5, expiry, 0);
}

static endFlatbuffersStream(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createFlatbuffersStream(builder:flatbuffers.Builder, createdAt:number, payloadOffset:flatbuffers.Offset, deviceTypeOffset:flatbuffers.Offset, deviceIdOffset:flatbuffers.Offset, deliveredAtEpochMs:bigint, expiry:number):flatbuffers.Offset {
  FlatbuffersStream.startFlatbuffersStream(builder);
  FlatbuffersStream.addCreatedAt(builder, createdAt);
  FlatbuffersStream.addPayload(builder, payloadOffset);
  FlatbuffersStream.addDeviceType(builder, deviceTypeOffset);
  FlatbuffersStream.addDeviceId(builder, deviceIdOffset);
  FlatbuffersStream.addDeliveredAtEpochMs(builder, deliveredAtEpochMs);
  FlatbuffersStream.addExpiry(builder, expiry);
  return FlatbuffersStream.endFlatbuffersStream(builder);
}
}
