// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from "flatbuffers";

import {
  Message
} from "../flatbuffersmsg/message";

export class FlatbuffersEnvelope {
  bb: flatbuffers.ByteBuffer | null = null;
  bb_pos = 0;
  __init(i: number, bb: flatbuffers.ByteBuffer): FlatbuffersEnvelope {
    this.bb_pos = i;
    this.bb = bb;
    return this;
  }

  static getRootAsFlatbuffersEnvelope(
    bb: flatbuffers.ByteBuffer,
    obj?: FlatbuffersEnvelope,
  ): FlatbuffersEnvelope {
    return (obj || new FlatbuffersEnvelope()).__init(
      bb.readInt32(bb.position()) + bb.position(),
      bb,
    );
  }

  static getSizePrefixedRootAsFlatbuffersEnvelope(
    bb: flatbuffers.ByteBuffer,
    obj?: FlatbuffersEnvelope,
  ): FlatbuffersEnvelope {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
    return (obj || new FlatbuffersEnvelope()).__init(
      bb.readInt32(bb.position()) + bb.position(),
      bb,
    );
  }

  /**
   * txid: unique transaction id of this message
   */
  txid(index: number): number | null {
    const offset = this.bb!.__offset(this.bb_pos, 4);
    return offset
      ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index)
      : 0;
  }

  txidLength(): number {
    const offset = this.bb!.__offset(this.bb_pos, 4);
    return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
  }

  txidArray(): Uint8Array | null {
    const offset = this.bb!.__offset(this.bb_pos, 4);
    return offset
      ? new Uint8Array(
          this.bb!.bytes().buffer,
          this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset),
          this.bb!.__vector_len(this.bb_pos + offset),
        )
      : null;
  }

  /**
   * topic: used for rooting messages to backend queues
   */
  topic(index: number): number | null {
    const offset = this.bb!.__offset(this.bb_pos, 6);
    return offset
      ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index)
      : 0;
  }

  topicLength(): number {
    const offset = this.bb!.__offset(this.bb_pos, 6);
    return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
  }

  topicArray(): Uint8Array | null {
    const offset = this.bb!.__offset(this.bb_pos, 6);
    return offset
      ? new Uint8Array(
          this.bb!.bytes().buffer,
          this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset),
          this.bb!.__vector_len(this.bb_pos + offset),
        )
      : null;
  }

  messageType(): Message {
    const offset = this.bb!.__offset(this.bb_pos, 8);
    return offset ? this.bb!.readUint8(this.bb_pos + offset) : Message.NONE;
  }

  /**
   * message: type of message
   */
  message<T extends flatbuffers.Table>(obj: any): any | null {
    const offset = this.bb!.__offset(this.bb_pos, 10);
    return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
  }

  /**
   * message_id: unique id of this message
   */
  messageId(index: number): number | null {
    const offset = this.bb!.__offset(this.bb_pos, 12);
    return offset
      ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index)
      : 0;
  }

  messageIdLength(): number {
    const offset = this.bb!.__offset(this.bb_pos, 12);
    return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
  }

  messageIdArray(): Uint8Array | null {
    const offset = this.bb!.__offset(this.bb_pos, 12);
    return offset
      ? new Uint8Array(
          this.bb!.bytes().buffer,
          this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset),
          this.bb!.__vector_len(this.bb_pos + offset),
        )
      : null;
  }

  static startFlatbuffersEnvelope(builder: flatbuffers.Builder) {
    builder.startObject(5);
  }

  static addTxid(builder: flatbuffers.Builder, txidOffset: flatbuffers.Offset) {
    builder.addFieldOffset(0, txidOffset, 0);
  }

  static createTxidVector(
    builder: flatbuffers.Builder,
    data: number[] | Uint8Array,
  ): flatbuffers.Offset {
    builder.startVector(1, data.length, 1);
    for (let i = data.length - 1; i >= 0; i--) {
      builder.addInt8(data[i]!);
    }
    return builder.endVector();
  }

  static startTxidVector(builder: flatbuffers.Builder, numElems: number) {
    builder.startVector(1, numElems, 1);
  }

  static addTopic(
    builder: flatbuffers.Builder,
    topicOffset: flatbuffers.Offset,
  ) {
    builder.addFieldOffset(1, topicOffset, 0);
  }

  static createTopicVector(
    builder: flatbuffers.Builder,
    data: number[] | Uint8Array,
  ): flatbuffers.Offset {
    builder.startVector(1, data.length, 1);
    for (let i = data.length - 1; i >= 0; i--) {
      builder.addInt8(data[i]!);
    }
    return builder.endVector();
  }

  static startTopicVector(builder: flatbuffers.Builder, numElems: number) {
    builder.startVector(1, numElems, 1);
  }

  static addMessageType(builder: flatbuffers.Builder, messageType: Message) {
    builder.addFieldInt8(2, messageType, Message.NONE);
  }

  static addMessage(
    builder: flatbuffers.Builder,
    messageOffset: flatbuffers.Offset,
  ) {
    builder.addFieldOffset(3, messageOffset, 0);
  }

  static addMessageId(
    builder: flatbuffers.Builder,
    messageIdOffset: flatbuffers.Offset,
  ) {
    builder.addFieldOffset(4, messageIdOffset, 0);
  }

  static createMessageIdVector(
    builder: flatbuffers.Builder,
    data: number[] | Uint8Array,
  ): flatbuffers.Offset {
    builder.startVector(1, data.length, 1);
    for (let i = data.length - 1; i >= 0; i--) {
      builder.addInt8(data[i]!);
    }
    return builder.endVector();
  }

  static startMessageIdVector(builder: flatbuffers.Builder, numElems: number) {
    builder.startVector(1, numElems, 1);
  }

  static endFlatbuffersEnvelope(
    builder: flatbuffers.Builder,
  ): flatbuffers.Offset {
    const offset = builder.endObject();
    return offset;
  }

  static finishFlatbuffersEnvelopeBuffer(
    builder: flatbuffers.Builder,
    offset: flatbuffers.Offset,
  ) {
    builder.finish(offset);
  }

  static finishSizePrefixedFlatbuffersEnvelopeBuffer(
    builder: flatbuffers.Builder,
    offset: flatbuffers.Offset,
  ) {
    builder.finish(offset, undefined, true);
  }

  static createFlatbuffersEnvelope(
    builder: flatbuffers.Builder,
    txidOffset: flatbuffers.Offset,
    topicOffset: flatbuffers.Offset,
    messageType: Message,
    messageOffset: flatbuffers.Offset,
    messageIdOffset: flatbuffers.Offset,
  ): flatbuffers.Offset {
    FlatbuffersEnvelope.startFlatbuffersEnvelope(builder);
    FlatbuffersEnvelope.addTxid(builder, txidOffset);
    FlatbuffersEnvelope.addTopic(builder, topicOffset);
    FlatbuffersEnvelope.addMessageType(builder, messageType);
    FlatbuffersEnvelope.addMessage(builder, messageOffset);
    FlatbuffersEnvelope.addMessageId(builder, messageIdOffset);
    return FlatbuffersEnvelope.endFlatbuffersEnvelope(builder);
  }
}
