// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { FlatbuffersCommand } from "../flatbuffersmsg/flatbuffers-command";
import { FlatbuffersStream } from "../flatbuffersmsg/flatbuffers-stream";
import { FlatbuffersStreamAck } from "../flatbuffersmsg/flatbuffers-stream-ack";
import { FlatbuffersSubscribe } from "../flatbuffersmsg/flatbuffers-subscribe";
import { FlatbuffersUnsubscribe } from "../flatbuffersmsg/flatbuffers-unsubscribe";

export enum Message {
  NONE = 0,
  FlatbuffersSubscribe = 1,
  FlatbuffersUnsubscribe = 2,
  FlatbuffersCommand = 3,
  FlatbuffersStream = 4,
  FlatbuffersStreamAck = 5,
}

export function unionToMessage(
  type: Message,
  accessor: (
    obj:
      | FlatbuffersCommand
      | FlatbuffersStream
      | FlatbuffersStreamAck
      | FlatbuffersSubscribe
      | FlatbuffersUnsubscribe,
  ) =>
    | FlatbuffersCommand
    | FlatbuffersStream
    | FlatbuffersStreamAck
    | FlatbuffersSubscribe
    | FlatbuffersUnsubscribe
    | null,
):
  | FlatbuffersCommand
  | FlatbuffersStream
  | FlatbuffersStreamAck
  | FlatbuffersSubscribe
  | FlatbuffersUnsubscribe
  | null {
  switch (Message[type]) {
    case "NONE":
      return null;
    case "FlatbuffersSubscribe":
      return accessor(new FlatbuffersSubscribe())! as FlatbuffersSubscribe;
    case "FlatbuffersUnsubscribe":
      return accessor(new FlatbuffersUnsubscribe())! as FlatbuffersUnsubscribe;
    case "FlatbuffersCommand":
      return accessor(new FlatbuffersCommand())! as FlatbuffersCommand;
    case "FlatbuffersStream":
      return accessor(new FlatbuffersStream())! as FlatbuffersStream;
    case "FlatbuffersStreamAck":
      return accessor(new FlatbuffersStreamAck())! as FlatbuffersStreamAck;
    default:
      return null;
  }
}

export function unionListToMessage(
  type: Message,
  accessor: (
    index: number,
    obj:
      | FlatbuffersCommand
      | FlatbuffersStream
      | FlatbuffersStreamAck
      | FlatbuffersSubscribe
      | FlatbuffersUnsubscribe,
  ) =>
    | FlatbuffersCommand
    | FlatbuffersStream
    | FlatbuffersStreamAck
    | FlatbuffersSubscribe
    | FlatbuffersUnsubscribe
    | null,
  index: number,
):
  | FlatbuffersCommand
  | FlatbuffersStream
  | FlatbuffersStreamAck
  | FlatbuffersSubscribe
  | FlatbuffersUnsubscribe
  | null {
  switch (Message[type]) {
    case "NONE":
      return null;
    case "FlatbuffersSubscribe":
      return accessor(
        index,
        new FlatbuffersSubscribe(),
      )! as FlatbuffersSubscribe;
    case "FlatbuffersUnsubscribe":
      return accessor(
        index,
        new FlatbuffersUnsubscribe(),
      )! as FlatbuffersUnsubscribe;
    case "FlatbuffersCommand":
      return accessor(index, new FlatbuffersCommand())! as FlatbuffersCommand;
    case "FlatbuffersStream":
      return accessor(index, new FlatbuffersStream())! as FlatbuffersStream;
    case "FlatbuffersStreamAck":
      return accessor(
        index,
        new FlatbuffersStreamAck(),
      )! as FlatbuffersStreamAck;
    default:
      return null;
  }
}
